### ISSUE TITLE
layout=html broken after plugin update

### ISSUE THREAD

**Issue by tmo26** [mprins/pagequery#10]
## environment

  - php version: 7.4.25
  - dokuwiki version: Release 2020-07-29 "Hogfather"
  - plugin version / date: 2022-02-05
  - list of any other plugins (apart from bundled plugins): 
```
plugin	a2s
plugin	abbr
plugin	acl
plugin	addnewpage
plugin	authmysql
plugin	authorstats
plugin	authpgsql
plugin	authplain
plugin	batchedit
plugin	bureaucracy
plugin	captcha
plugin	catlist
plugin	cellbg
plugin	cleanup
plugin	clearhistory
plugin	cloud
plugin	color
plugin	columns
plugin	comment
plugin	config
plugin	cookielaw
plugin	csv
plugin	custombuttons
plugin	data
plugin	datatables
plugin	datatemplate
plugin	ditaa
plugin	docnavigation
plugin	enforcesummary
plugin	extension
plugin	feed
plugin	filelist
plugin	folded
plugin	gchart
plugin	gdpr
plugin	gh
plugin	hidden
plugin	hiddenheader
plugin	hidepages
plugin	iframe
plugin	imagemapping
plugin	include
plugin	info
plugin	interwikipaste
plugin	ipban
plugin	loglog
plugin	maintenancemessage
plugin	meta
plugin	move
plugin	multiorphan
plugin	mysql
plugin	nosidebar
plugin	nslist
plugin	nspages
plugin	oauth
plugin	orphanswanted
plugin	outliner
plugin	pagelist
plugin	pagequery
plugin	passpolicy
plugin	popularity
plugin	prettytables
plugin	redirect
plugin	revert
plugin	safefnrecode
plugin	searchdefaults
plugin	searchform
plugin	searchindex
plugin	searchtablejs
plugin	semantic
plugin	smtp
plugin	sortablejs
plugin	sqlite
plugin	styling
plugin	tabbox
plugin	tag
plugin	tagalerts
plugin	toolbox
plugin	translation
plugin	unameban
plugin	upgrade
plugin	userhistory
plugin	usermanager
plugin	vshare
plugin	webcode
plugin	wrap
```
  
## expected behaviour

Display of pagequery result as shown: All pagequery results listed nicely in one column (page shows 2 pagequeries in combination with columns-plugin)
![grafik](https://user-images.githubusercontent.com/12309103/163807852-4a253ec5-8da1-4e22-a8e1-2ab67316425a.png)

This is the expected and actual behaviour pre-updating to 2022-02-05

## actual behaviour

Note: This happens with and without `layout=html`; `layout=column` does not show this behaviour, but renders the column way too small, without possibility to increase column width -> `layout=column` is not suitable as replacement for `layout=html`)

Display of pagequery result as shown (**in combination** with columns-plugin): One (and only one!) item of each pagequery column content gets shown above the column
![grafik](https://user-images.githubusercontent.com/12309103/163807923-8794ce29-ee82-487a-b3ec-8c38aacdab76.png)

Display of pagequery result as shown (**without** combination with columns-plugin): One (and only one!) item of each pagequery column content gets shown below the column
![grafik](https://user-images.githubusercontent.com/12309103/163808294-2c6d7ead-c919-427e-be06-f2c0b97d074b.png)

## steps to reproduce actual behaviour

```
{{pagequery>* @:toh:avm;
cols=1;
sort=title;
hidestart;
hidejump;
maxns=2;
display={title};
bullet=disc;
}}
```

### error log

```
No errors shown in php or nginx logs
```

### debug log

```
DEBUG
```

**Comment by Lethert** [comment]
same in my wiki systems after update. I rollback to the old version, that works!

**Comment by mprins** [comment]
Sorry I don't have an environment to analyse this problem and there seems to be a relation to the columns-plugin; your images are just that, they do not provide the rendered html.

The changes between 2021-12-31 and 2022-02-05 are mostly geared to supporting php 8 and since there were never any rendering unit tests in the original project the criteria for passing is if things work for me.

eg. using `{{pagequery>@beschrijvingen ^beschrijvingen:regio -index;fulltext;proper;sort=a,name;group;hidestart;cols=2}}` in https://wild-water.nl/dokuwiki/beschrijvingen/index

**Comment by tmo26** [comment]
> there seems to be a relation to the columns-plugin;

No, there is absolutely no connection to the columns plugin.
As shown above, the problem persists even when the columns-plugin syntax is removed from the page.
On top of that, I have even completely uninstalled the columns plugin, but the problem persists.

**Comment by mprins** [comment]
It seems there is no option `html` in the code, nor in the documentation of the pluging. As the docs says here: https://github.com/mprins/pagequery/blob/53d6e4b85fa10a1cc978e26d3f808d7d297e2ea4/syntax.php#L73 valid options are columns and table (table) being the default perhaps you've been using a different fork of the plugin
there is no function to do what you want, only 

https://github.com/mprins/pagequery/blob/53d6e4b85fa10a1cc978e26d3f808d7d297e2ea4/PageQuery.php#L786-L797
 
and 
https://github.com/mprins/pagequery/blob/53d6e4b85fa10a1cc978e26d3f808d7d297e2ea4/PageQuery.php#L1077-L1085

**Comment by Klap-in** [comment]
@Lethert could you provide an example of the syntax you are using?

**Comment by Lethert** [comment]
{{pagequery>*; label=Die letzten 10 Änderungen aus allen Bereichen; sort=mdate:desc; limit=10; bullet=square; display={title} -- {mdate}; hidestart; filter=!name:letzteaenderungen; snippet=inline,10,l2; fontsize=110%; underline; hidejump; }}
 
 
 
 
Von: Gerrit Uitslag ***@***.***> 
Gesendet: Dienstag, 16. August 2022 09:37
An: mprins/pagequery ***@***.***>
Cc: Lethert ***@***.***>; Mention ***@***.***>
Betreff: Re: [mprins/pagequery] layout=html broken after plugin update (Issue #10)
 
@Lethert could you provide an example of the syntax you are using?

**Comment by roelvanmeer** [comment]
PR https://github.com/mprins/pagequery/pull/15 fixed an issue with the addHeading function. This might be relevant for your problem.

**Comment by desbest** [comment]
I have the same issue as well.
Also this issue has turned 1 year old TODAY, so now would be a good time for me to fix it.
I'll start work on it, later this month.
Is there anyone here who can volunteer for testing?

**Comment by punk-t** [comment]
Hello @desbest 
I own two independent instances of DW / pagequery, both usable for testing purposes.
I'll join.

**Comment by desbest** [comment]
I've fixed it from my end. I'm just waiting for the maintainer to approve my pull request.

**Comment by desbest** [comment]
It should be done now. Just to make sure, I tested it again for a second time, at the very end.
@punk-t Try testing it on your end.

**Comment by mprins** [comment]
had to revert @desbest PR because it caused problems for me and others:

- https://github.com/mprins/pagequery/pull/17#issuecomment-1516844940
- https://github.com/mprins/pagequery/pull/17#issuecomment-1517613735

**Comment by desbest** [comment]
So my first pull request was approved however my second pull request was rejected.
It seems like I'm seeing some sort of bug or visual quirk, that you lot aren't seeing.

@mprins @punk-t So my question is, does the plugin work, is the layout fixed and most importantly, are you seeing those weird symbols on your screen?

I've just upgraded to the latest version of the plugin, that was just released today and here's what I see. Below is the corresponding syntax tag.

```
{{pagequery>@:testbook *;fontsize=1.35em;hidestart;hidejump;snippet;showcount;bullet=square;sort=a:asc;heading;display={title}  }}
```
![pagequery visual quirks 1](https://user-images.githubusercontent.com/1139316/233628124-3e571918-f0e7-4f63-ac89-461cefa26f1a.png)

It's interesting how the _before and after_ of [what @mprins saw before and after the 2nd pull request](https://github.com/mprins/pagequery/pull/17#issuecomment-1517613735), is the complete opposite of what I saw, from good to bad or bad to good.

**Comment by mprins** [comment]
you misunderstand; my before is the version from before any of your PR's and which I consider a working version.
Perhaps you could add rendering tests to the plugin to make sure things behave as expected

**Comment by desbest** [comment]
What syntax for the `<pagequery>` tag are you using @mprins ?

**Comment by Klap-in** [comment]
Are you both testing with different templates?

**Comment by desbest** [comment]
Yes it even happens to me on the default theme.

![pagequery visual quirks 2](https://user-images.githubusercontent.com/1139316/233790371-fdb73ef2-bd20-46fd-9e2e-f45207367d3c.png)

**Comment by desbest** [comment]
@Klap-in So what `<pagequery>` syntax are you using?

**Comment by mprins** [comment]
> What syntax for the `<pagequery>` tag are you using...

a written here: https://github.com/mprins/pagequery/pull/17#issuecomment-1517613735 
 `{{pagequery>@beschrijvingen ^beschrijvingen:regio -index;fulltext;proper;sort=a,name;group;hidestart;cols=2}}`
using `arctic`  template, see https://wild-water.nl/dokuwiki/beschrijvingen/index

**Comment by desbest** [comment]
I'll start work on fixing it for the both of us in May.

**Comment by Klap-in** [comment]
> @Klap-in So what `<pagequery>` syntax are you using?

Sorry, I'm not using this plugin.
