### ISSUE TITLE
display={date:created} {title}

### ISSUE THREAD

**Issue by tangilab** [mprins/pagequery#4]
Hello, the `display` argument does not work for me since the last update.
I have installed it on a new server, without more results.
Usually the first title of first level (H1) is displayed instead of the spacename with `display={title};` it is not the case anymore, only the spacename is displayed.

For exemple

`{{pagequery>@lapin; fulltext; display={date:created} {title};sort=title:asc; limit=100; bullet=square; proper; }}`

![Capture d’écran 2022-01-19 150225](https://user-images.githubusercontent.com/57544414/150146080-190ca912-2300-44ea-8132-686eff33bd36.png)

![Capture d’écran 2022-01-19 150329](https://user-images.githubusercontent.com/57544414/150146119-7d9b4cf0-9c92-403d-9fe8-447cab2b3999.png)

**Comment by mprins** [comment]
please provide a proper pull request with a unit test; I'm not at home in this inherited and convoluted codebase.

this may be an API change in DW, making your suggested fix break with the current release candidate.

As you can see there is no function `html_wikilink` that takes a boolean as the second argument: https://xref.dokuwiki.org/reference/dokuwiki/inc/html.php.source.html#l34

**Comment by Klap-in** [comment]
The xref page will near future be replaced by the code search page. Which more up to date, and let you search in all plugin code eventually.
https://codesearch.dokuwiki.org/search?project=dokuwiki&full=Html_wikilink

**Comment by mprins** [comment]
this should be fixed with #11, if not please reopen
