### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by arlt** [mprins/pagequery#5]
## environment

  - php version: 7.3
  - dokuwiki version: Hogfather
  
## expected behaviour

Should work with same PHP version as Hogfather.
Even the upcoming release "Igor": " Drop support for PHP versions earlier than 7.2"

## actual behaviour

According to https://www.dokuwiki.org/plugin:pagequery PHP 7.4 is required

**Comment by mprins** [comment]
> php version: 7.3

this is no longer supported
