### ISSUE TITLE
Update breaks Dokuwiki

### ISSUE THREAD

**Issue by chefschaffner** [mprins/pagequery#7]
## environment

  - php version:  7.3.31-1
  - dokuwiki version: 2020-07-29 "Hogfather"
  - plugin version / date:  latest (2022-02-05)
  - list of any other plugins (apart from bundled plugins): 
  vshare           move         loglog     authmysql   revert      authad       action.php    searchindex    wrap         editor    s5        edittable  blockquote
siteexport       dw2pdf       fastwiki   extension   cli.php     usermanager  authldap      custombuttons  odt          toctweak  pagelist  dir        autologoff
pagequery.tgz    csv          icons      authpdo     info        authplain    admin.php     todo           gallery      text      pagehere  comment    authorlist
outliner         bookcreator  authpgsql  remote.php  popularity  acl          safefnrecode  farmer         authchained  tag       imgpaste  columns    addnewpage
newpagetemplate  qna          styling    auth.php    syntax.php  config       upgrade       folded         task         sync      emphasis  cloud      
  
## expected behaviour
Update works without bracking dokuwiki

## actual behaviour
After Upgrade the Dokuwiki page gives Error 500. After removing the directory "pagequery", dokuwiki is working fine again.

## steps to reproduce actual behaviour
Upgrade pagequery

### error log

```
[Wed Mar 02 10:39:38.085558 2022] [:error] [pid 20989] [client 10.180.42.238:61794] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /opt/wiki/lib/plugins/upgrade/HTTPClient.php on line 579, referer: https://gsmrbo2.bku-web.db.de/wiki/doku.php?id=start&do=admin&page=upgrade
[Wed Mar 02 10:40:39.137462 2022] [:error] [pid 30563] [client 10.180.42.238:61854] PHP Fatal error:  Uncaught TypeError: Return value of syntax_plugin_pagequery::connectTo() must be an instance of void, none returned in /opt/wiki/lib/plugins/pagequery/syntax.php:35\nStack trace:\n#0 /opt/wiki/inc/Parsing/Parser.php(88): syntax_plugin_pagequery->connectTo('base')\n#1 /opt/wiki/inc/Parsing/Parser.php(106): dokuwiki\\Parsing\\Parser->connectModes()\n#2 /opt/wiki/inc/parserutils.php(216): dokuwiki\\Parsing\\Parser->parse('====== Bitte Li...')\n#3 /opt/wiki/inc/parserutils.php(181): p_get_instructions('====== Bitte Li...')\n#4 /opt/wiki/inc/parserutils.php(501): p_cached_instructions('/opt/wiki/data/...', false, 'start')\n#5 /opt/wiki/inc/parserutils.php(282): p_render_metadata('start', Array)\n#6 /opt/wiki/inc/common.php(244): p_get_metadata('start')\n#7 /opt/wiki/doku.php(93): pageinfo()\n#8 {main}\n  thrown in /opt/wiki/lib/plugins/pagequery/syntax.php on line 35, referer: https://gsmrbo2.bku-web.db.de/wiki/doku.php?id=start&do=admin&page=extension&tab=plugins

```

### debug log
```

```

**Comment by arlt** [comment]
see #5

**Comment by mprins** [comment]
> php version: 7.3.31-1

this is no longer supported, you can try old versions of the plugin if you like
