### ISSUE TITLE
Not working for me: Display, Sorting

### ISSUE THREAD

**Issue by schnuckovic** [mprins/pagequery#9]
## environment

  - php version: 7.4.28
  - dokuwiki version: Release 2020-07-29 "Hogfather"
  - plugin version / date: latest as of 2022-03-30

  
## expected behaviour

Display {name} {date:created}, etc.

Sort ascending, descending: sort=mdate:asc, etc.

## actual behaviour

No matter what I tell it to do, it doesn't sort. It's always newest at the bottom.

### error log

No errors thrown.

No debug configured.

## Quick Fix: Reinstall old version

Installed the old version from MrBertie: https://github.com/MrBertie/pagequery

Works as expected. 

## Future 

What's the plan? 

I take it not many people use this plugin. I do, and I was happy that someone took it over to improve, continue development. However, status quo does not help, at least not for me.

**Comment by User220419** [comment]
I've got the same problem here.

**Comment by Lethert** [comment]
same for me on diferent wiki-Systems.

After Update sort not working!

**Comment by mprins** [comment]
This works for me: `{{pagequery>@beschrijvingen ^beschrijvingen:regio -index;fulltext;proper;sort=a,name;group;hidestart;cols=2}}` in https://wild-water.nl/dokuwiki/beschrijvingen/index

You are welcome to provide a pull request with a fix an preferably a unittest as well.

**Comment by schnuckovic** [comment]
I have this, e.g.:

{{pagequery>@:protokolle *;sort=name:desc;limit=3;hidestart;display={name}:  {title};hidejump;fontsize=120%;snippet=quoted,1000,l1}}

Result is not in descending order, it returns the oldest dates (format: 2022-07-06), not the youngest. Changing desc to asc has no effect.

Result does not display={name}:  {title} but only the title. 

Thus sorting and displaying got broken somehow. Above code works with the old version.

**Comment by Klap-in** [comment]
@Lethert and @User220419 please could you provide examples of the syntax you are using?

**Comment by Herbs851** [comment]
Hi all,

My own experience after update with this query : 

```
{{pagequery>;hidestart;sort=mdate;filter=!title:.*(_|sidebar).*;limit=10;proper=header;display={date:modified} : {title};bullet=square;hidejump;fontsize=102%;}}
```

Before update : 

![image](https://user-images.githubusercontent.com/51154851/187038988-bc38420e-1d72-4c51-883b-6b9c50a2f616.png)

After update : 

![image](https://user-images.githubusercontent.com/51154851/187039004-986373b2-c89a-4787-9291-1b914e50fefa.png)

**Comment by mschlenstedt** [comment]
Yes, same here: no sorting, no grouping. Mr.Bertie Version works fine.

**Comment by CADcoder** [comment]
same for me: after reinstalling Mr.Bertie Version script works as expected. Thanks @schnuckovic for the hint.

**Comment by Herbs851** [comment]
Hi @mprins 

Thanks for this update.

It's better but there's still a problem : 

![image](https://user-images.githubusercontent.com/51154851/212160445-dae00ecd-775f-4fd8-aab8-5f3430b0408e.png)

If I reduce the limit to 9 instead of 10 the display is correct.
